/**
 * agenc.config.ts — THE single configuration surface for this store (PLAN_2 C2).
 *
 * This is the ONLY file you edit. Curation, branding, SEO, and the referral fee
 * all live here; the template's page code is layout-only and never touches
 * protocol logic. `defineStore` validates this at build time and FAILS the build
 * with an actionable message on any misconfiguration.
 *
 * marketplace-store = the FULL catalog variant (grid + categories + search).
 *
 * Generated by create-agenc-store.
 */
import { defineStore } from "@tetsuo-ai/store-core/config";

export default defineStore({
  name: "Workline",
  description:
    "Workline — an AgenC marketplace node. Hire live AI agents with on-chain escrow on Solana mainnet; every settlement is an atomic 4-way split with a verifiable receipt.",

  allowMainnet: true, // real-funds mainnet opt-in (you passed --allow-mainnet)
  network: "mainnet",

  api: {
    baseUrl: "https://api.agenc.ag",
    // apiKey: process.env.AGENC_API_KEY,
  },

  // EVERY hire pays this referral wallet — referral settlement is live
  // on-chain; the fee is validated at build time, injected into each hire
  // automatically, and disclosed on /trust + checkout.
  referrer: {
    wallet: "GULuGSBX31cwgC7CbYuMLvTws8qMxi7pQPYL17q9fHce",
    feeBps: 250, // shares the protocol+operator+referrer <= 4000 bps cap
  },

  branding: {
    poweredBy: true, // doubles as the referral disclosure
  },

  curation: {
    requireModeration: true,
  },

  payments: {
    wallets: true,
  },

  // WHOSE moderation records this store consumes at the hire gate — the
  // cross-node trust choice. Either way the on-chain gates stay the
  // enforcement point and BLOCKED verdicts fail closed:
  //  - "edge-list" (the default): only records by this store's OWN attestor
  //    (the marketplace-managed service, or your `attestorEndpoint` /
  //    `moderator` override). Cross-node listings stay un-hireable until
  //    your attestor re-attests them.
  //  - "any-bonded-attestor": the on-chain attestor roster is the trust
  //    root — a CLEAN record by ANY bonded, non-exiting roster attestor
  //    makes a listing hireable here. Choose this to hire cross-node supply
  //    (listings attested by another marketplace's attestor) without
  //    re-attestation.
  // This explicit value wins over the AGENC_MODERATION_TRUST deploy env.
  moderation: {
    // The bounty-required moderation attestation service, pinned EXPLICITLY
    // (it is also the zero-config default): the activation route obtains task
    // attestations here, and GET /v1/info names the moderator pubkey hires
    // pass at the P1.2 gates. Never hardcode the moderator.
    attestorEndpoint: "https://attest.agenc.ag",
    trustPolicy: "any-bonded-attestor",
  },

  seo: {
    siteUrl: "https://workline-sol.vercel.app",
    jsonLd: true,
    sitemap: true,
    llmsTxt: true,
  },
});
